apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: my-test2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: my-test2
    app.kubernetes.io/part-of: my-test2
  name: my-test2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: my-test2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: my-test2
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mkosiarc-tenant/my-test2/my-test2@sha256:d3b1ce2fb3b9ceb739cce39c9dda77cdb5076792e4d8ea9f263c93095521bd55
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
